Algoritmo "Soma"
//  
//  

// Descrição   : Somar 3 números inteiro e calcular a soma deles:
// Autor(a)    : Herta França
// Data atual  : 29/07/2026
Var
 number1,number2,number3,add:inteiro

Inicio
// Entreada de dados /comando das variáveis:
escreva("Digite um valor:")
leia(number1)
escreva("Digite outro valor:")
leia(number2)
escreva ("Digite o último valor:")
leia(number3)

//Processamento de dados /Execução da função:
add<- number1 + number2 + number3

//Saída de resultados / resposta do comando:
escreval("A soma é:", add)

Fimalgoritmo
