Algoritmo "Conversão"
// 
//  
// Descrição   : Programar a converção de euro em dólares. sabendo que a
//taxa de conversão é de; euro=1,17 dólares.
// Autor(a)    : Herta Fraça
// Data atual  : 29/07/2026
Var
valorEuro,conversao:real


Inicio
// Entrada de dados: não deve colocar acento nas variáveis.
escreva("Digite o valor do Euro:")
leia(valorEuro)

// Processamento dos dados:
conversao<-(valorEuro*1.17)

//Saída de dados:
escreva("O valor convertido para dólar é: ", conversao)



Fimalgoritmo