Algoritmo "Converter temperatura ( FAHRENHEIT)

// Descrição   : Converter temperatura em grau Celsius para Fahrenheit:! (função)
// Autor(a)    : Herta França
// Data atual  : 02/09/2026
Var
// Criar as variáveis:

celsiusGraus:real
fahrenheit:real

Inicio
// Seção de Comandos: Entrada de dados, procedimento, funções, operadores, etc...

Escreva( "Digite a temperatura em graus Celsius:")
leia(celsiusGraus)
fahrenheit<-(9/5)*(celsiusGraus)+32
escreva("A temperatura convertida em Fahrenheit é:",fahrenheit)

Fimalgoritmo