Algoritmo "Média"
//  
//  

// Descrição   : Dada 3 notas, calcula a média
// Autor(a)    : Fenanda Torres
// Data atual  : 15/07/2026

Var

// Criação da variável:

P1: Inteiro
P2: Inteiro
P3: Inteiro
Media: real

Inicio

// Entrada de dados,procedimentos e saídas.

// Dados:

Escreval("Primeira Nota")
leia (p1)
Escreval("Segunda Nota")
leia (p2)
Escreval("Terceira Nota")
leia (p3)

Media<-(p1+p2+p3)/3
escreva (" A média é:)

Fimalgoritmo