Algoritmo "Média dos Alunos"

// Descrição   : Calcule as três notas de um aluno e diga qual foi a média:
// Autor(a)    : Herta França
// Data atual  : 29/07/2026
Var
bimester1, bimester2,bimester3:inteiro
media:real


Inicio

//  Entrada de dados:
escreva("Digite a primeira nota:")
leia(bimester1)
escreva("Digite a segunda nota:")
leia(bimester2)
escreva("Digite a terceira nota:")
leia(bimester3)

// Processamento dos dados:

media<- (bimester1 + bimester2 + bimester3 ) /3

//Saída de dados:
escreva(media)


Fimalgoritmo