Algoritmo "Peso Ideal 2"
//  
//  
// 
//  
// Descrição   : Calcular o peso ideal! (função)
// Autor(a)    : Herta França
// Data atual  : 02/09/2026
Var
// Criação das variáveis:
 hight:real
 idealWeight:real

Inicio
// Seção de Comandos e entrada de dados, procedimento, funções, operadores, etc...
 escreva("Digite sua altura:")
 leia(hight)
 idealWeight<-(72.7*hight)-58
 escreva("Seu peso ideal é:",idealWeight)
 
Fimalgoritmo