Algoritmo "Peso"
//  
//  

//Desafio 2
// Descrição   : Acha o peso ideal de uma pessoa de acordo com sua altura.
// Autor(a)    : Herta França
// Data atual  : 15/07/2026

Var

// Criação das variáveis:

Al:real
pesoIdeal:real

Inicio

// Entrada de dados,procedimentos, resultados e saída.

Escreval("Qual é sua altura?")
leia(Al)
pesoIdeal<-(72.7*Al)-58
Escreval("Seu peso ideal é:",pesoIdeal)


Fimalgoritmo