Algoritmo "Positivo ou Negativo"
// Disciplina   : Desenvolvendo Algoritmo
// Professor   : José Quelha
// Descrição   : Determinar se o número é negativo ou positivo! (função)
// Autor(a)    : Herta França.
// Data atual  : 09/09/2026
Var
// Seção de Declarações das variáveis 

 number:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval("Digite um número:")
Leia(number)

  se number > 0 entao
     escreval("Esse número é positivo:",number)
  
  senao
  
  se number < 0 entao
     escreval("Esse número é negativo:",number)
  
  senao
  
     escreval(" Esse número é neutro:", number)
  fimse
fimse


Fimalgoritmo