Algoritmo "Tipos de Números(Par ou íMPAR)"

//Disciplina : Desenvolvimento Algoritmos.
// Descrição   : Determine se o número é Par ou ímpar! (função)
// Autor(a)    : Herta França.
// Data atual  : 09/09/2026
Var
// Seção de Declarações das variáveis 
number, even, odd, type:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreva("Digite um valor:")
Leia(number)

     se number % 2 =! 0
       
      escreva ("Seu número é ímpar:",odd)
   
      senão

      escreva ("Seu número é par :",even)

   fimse


Fimalgoritmo