Algoritmo "Tipos de Número(Par ou ímpar)"

//Disciplina : Desenvolvimento Algoritmos.
// Descrisao  : Determine se o número é par ou ímpar.!
// Autor(a)    : Herta França
// Data atual  : 09/09/2026
Var
//
number:inteiro


Inicio
//  de Comandos, procedimento, operadores, etc...

Escreva("Digite um valor:")

Leia(number)

     se number % 2 <> 0 entao
       
      escreva ("Seu número é impar:",number)
   
      senao

      escreva ("Seu número é par :",number)

   fimse


Fimalgoritmo